config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/lists")

  devise_for :users

  resources :todo_lists, path: "lists" do
    resources :todo_items, path: "items", shallow: true do
      member do
        put :mark_complete
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user

    can :manage, TodoList
    can :manage, TodoItem
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  validates :todo_list_id, presence: true
  validates :title,        presence: true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user

  has_many :todo_items, dependent: :destroy

  validates :name, presence: true

  delegate :to_s, to: :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Also :recoverable and :trackable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to "/users/sign_in", alert: exception.message
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  load_and_authorize_resource :todo_list
  load_and_authorize_resource through: :todo_list, shallow: true

  def show
    # AJAX requests just get a snippet of HTML representing the item
    if request.xhr?
      render partial: @todo_item
      return
    end

    # Non AJAX requests probably want to see the whole list
    redirect_to @todo_item.todo_list
  end

  def create
    if @todo_item.save
      flash[:notice] = "Item added"
      redirect_to @todo_item.todo_list
    else
      flash[:error] = "Item couldn't be added"
      redirect_to @todo_item.todo_list
    end
  end

  # JSON API endpoint for AJAX update
  def mark_complete
    return :unprocessable_entity if @todo_item.completed?

    success = @todo_item.update(completed: true)

    respond_to do |format|
      format.json do
        if success
          render json: @todo_item
        else
          return :unprocessable_entity
        end
      end
    end
  end

  private

  def todo_item_params
    params.require(:todo_item).permit(:title, :description)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  # Use CanCanCan to preload the @todo_list variable if user is allowed to see it
  load_and_authorize_resource

  def index
  end

  def show
  end

  def new
  end

  def create
    if @todo_list.save
      flash[:notice] = "List created"
      redirect_to @todo_list
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @todo_list.update(todo_list_params)
      flash[:notice] = "List updated"
      redirect_to @todo_list
    else
      render "edit"
    end
  end

  def destroy
    if @todo_list.destroy
      flash[:notice] = format(%(List "%s" deleted), @todo_list)
      redirect_to todo_lists_url
    else
      flash[:error] = format(%(Couldn't delete list "%s"), @todo_list)
      redirect_to @todo_list
    end
  end

  private

  def todo_list_params
    params.require(:todo_list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_errors_for(object = nil)
    render("shared/errors", object: object) if object.present? && object.errors.any?
  end

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end

end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/_navbar.html.haml
/ Adapted from the Bootstrap example at http://getbootstrap.com/components/#navbar
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "To-dü", root_path, class: "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li
          = link_to "Your lists", todo_lists_path
        %li
          = link_to "Log out", destroy_user_session_path, method: :delete
      - else
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Gö!
            %span.caret
          %ul.dropdown-menu
            %li= link_to "Register", new_user_registration_path
            %li= link_to "Log in", new_user_session_path
  / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Todu
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .container
      = render "layouts/navbar"
      = flash_messages
      = yield

app/views/shared/_errors.html.haml
%p
  = pluralize(object.errors.size, "error")
  stopped this form being saved

%ul
  - object.errors.full_messages.each do |error|
    %li= error

app/views/todo_items/_form.html.haml
= form_for [todo_item.todo_list, todo_item], class: "" do |f|
  .form-group.todo-details
    = f.text_field :title, placeholder: "Title", autofocus: true, class: "form-control todo-title"
    -# = f.text_area :description, placeholder: "Description (optional)", class: "form-control todo-description"
  = f.submit "Add item", class: "btn btn-primary"

app/views/todo_items/_todo_item.html.haml
%div{ class: ("todo-item--completed" if todo_item.completed?) }
  = todo_item.title
  = link_to "I've döne it!", mark_complete_todo_item_path(todo_item), class: "js-mark-complete", method: :put

app/views/todo_items/mark_complete.js.erb
$("#<%= dom_id(@todo_item) %>").html("<%= j render(@todo_item) %>")

app/views/todo_lists/_form.html.haml
= form_for todo_list do |f|
  = form_errors_for(f.object)

  .form-group
    = f.label :name
    = f.text_field :name, autofocus: true, class: "form-control"

  = f.submit class: "btn btn-primary"

app/views/todo_lists/_todo_list.html.haml
.todo_list
  = link_to todo_list, todo_list

app/views/todo_lists/edit.html.haml
%h1 Edit list

= render partial: "form", locals: { todo_list: @todo_list }

app/views/todo_lists/index.html.haml
%h1 Lists

.list-group
  - @todo_lists.each do |list|
    = link_to list, class: "list-group-item" do
      = list
      .badge= list.todo_items.count

= link_to new_todo_list_path, class: "btn btn-default" do
  %span.glyphicon.glyphicon-plus
  New list

app/views/todo_lists/new.html.haml
%h1 New todo list

= render partial: "form", locals: { todo_list: @todo_list }

app/views/todo_lists/show.html.haml
%h1
  %span= @todo_list
  %span.small
    = link_to "Edit", [:edit, @todo_list], class: "btn btn-default"
    = link_to "Delete", @todo_list, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" }

.todo-items.list-group
  - @todo_list.todo_items.each do |todo_item|
    .list-group-item{class: "todo-item", id: dom_id(todo_item), data: {url: url_for(todo_item)}}
      = render todo_item
  .list-group-item
    = render partial: "todo_items/form", locals: { todo_item: @todo_list.todo_items.build }